import type {Client,ExpectedRevenueItem,Insight,Invoice,Project,Quote,RecurringService,RevenueForecast} from './types';
export const calculateQuoteWeightedValue=(q:Quote)=>q.amount*q.probability/100;
export function calculateMonthlyForecast(items:ExpectedRevenueItem[],quotes:Quote[]):RevenueForecast{const active=items.filter(i=>i.status!=='omitido');const floor=active.filter(i=>i.certainty==='asegurado').reduce((s,i)=>s+(i.amount??0),0);const weighted=quotes.filter(q=>!['rechazado','vencido'].includes(q.status)).reduce((s,q)=>s+calculateQuoteWeightedValue(q),0);return{floor,probable:floor+weighted,potential:floor+quotes.filter(q=>!['rechazado','vencido'].includes(q.status)).reduce((s,q)=>s+q.amount,0),undefinedCount:active.filter(i=>i.amount===null).length}}
export function generateExpectedRevenue(month:string,services:RecurringService[],projects:Project[]):ExpectedRevenueItem[]{return[...services.filter(s=>s.active).map(s=>({id:`exp-${month}-${s.id}`,clientId:s.clientId,month,amount:s.expectedAmount,source:'recurrente' as const,sourceId:s.id,certainty:(s.variability==='variable'?'probable':'asegurado') as 'probable'|'asegurado',status:(s.expectedAmount===null?'revisión':'esperado') as 'revisión'|'esperado'})),...projects.flatMap(p=>p.stages.filter(s=>s.expectedMonth===month&&!['facturada','cobrada'].includes(s.status)).map(s=>({id:`exp-${s.id}`,clientId:p.clientId,month,amount:s.amount,source:'proyecto' as const,sourceId:s.id,certainty:'asegurado' as const,status:(s.amount===null?'revisión':'esperado') as 'revisión'|'esperado'})))]}
export function calculateClientConcentration(invoices:Invoice[]){const total=invoices.reduce((s,i)=>s+i.amount,0);return Object.entries(invoices.reduce<Record<string,number>>((a,i)=>(a[i.clientId]=(a[i.clientId]||0)+i.amount,a),{})).map(([clientId,amount])=>({clientId,amount,share:total?amount/total:0})).sort((a,b)=>b.share-a.share)}
export function detectRecurringPatterns(invoices:Invoice[]){const grouped=invoices.reduce<Record<string,number[]>>((acc,invoice)=>{(acc[invoice.clientId]??=[]).push(invoice.amount);return acc},{});return Object.entries(grouped).filter(([,values])=>values.length>=3&&Math.max(...values)-Math.min(...values)<Math.max(...values)*.1).map(([clientId,values])=>({clientId,months:values.length,average:values.reduce((a,b)=>a+b,0)/values.length}))}
export function generateFinancialInsights(input:{clients:Client[];services:RecurringService[];projects:Project[];quotes:Quote[];invoices:Invoice[];month:string;target:number;forecast:RevenueForecast}):Insight[]{const out:Insight[]=[];const cs=calculateClientConcentration(input.invoices)[0];if(cs&&cs.share>.4)out.push({id:'concentration',type:'CLIENT_CONCENTRATION',severity:'warning',message:`${input.clients.find(c=>c.id===cs.clientId)?.name} representa ${Math.round(cs.share*100)}% de tu facturación.`,action:'Ver cliente'});input.projects.flatMap(p=>p.stages.map(s=>({p,s}))).filter(x=>x.s.expectedMonth===input.month&&x.s.amount===null).forEach(({p,s})=>out.push({id:s.id,type:'PROJECT_STAGE_DUE',severity:'warning',message:`No definiste el importe de ${s.name} · ${p.name}.`,action:'Definir importe'}));input.quotes.filter(q=>(Date.parse('2026-09-01')-Date.parse(q.lastFollowUp))/86400000>14&&!['aprobado','rechazado'].includes(q.status)).forEach(q=>out.push({id:q.id,type:'QUOTE_FOLLOWUP',severity:'info',message:`${q.name} necesita seguimiento comercial.`,action:'Registrar seguimiento'}));out.push({id:'target',type:input.forecast.probable>=input.target?'MONTH_ABOVE_TARGET':'MONTH_BELOW_TARGET',severity:input.forecast.probable>=input.target?'positive':'info',message:input.forecast.probable>=input.target?'La proyección probable supera tu objetivo mensual.':'La proyección probable aún está debajo del objetivo.',action:'Revisar oportunidades'});return out}
export const calculateAnnualProjection=(actual:number,forecast:RevenueForecast)=>({conservative:actual+forecast.floor*4,probable:actual+forecast.probable*4,potential:actual+forecast.potential*4});
export function matchInvoiceToExpectedRevenue(invoice:Invoice,items:ExpectedRevenueItem[]){return items.map(i=>({item:i,score:(i.clientId===invoice.clientId?60:0)+(i.amount===invoice.amount?30:0)+(i.month===invoice.date.slice(0,7)?10:0)})).sort((a,b)=>b.score-a.score)[0]}
