import {describe,expect,it} from 'vitest';
import {applyPayment,calculateMonthlyForecast,calculatePeriodComparison,createInvoiceFromRevenueSource,generateExpectedRevenue,generateFinancialInsights,getNetBilling,syncProjectStageFromInvoice} from './services';
import {clients,expressJobs,projects,quotes,services,settings} from '@/data/seed';
import type {Invoice,Payment,Quote} from './types';
const month='2026-09';
describe('motor financiero normalizado',()=>{
 it('incluye express confirmado en el forecast del mes',()=>{const items=generateExpectedRevenue(month,services,projects,expressJobs);expect(items.find(i=>i.source==='express')?.amount).toBe(180000);expect(calculateMonthlyForecast(month,items,[]).floor).toBe(3257245)});
 it('excluye express de otro mes',()=>expect(generateExpectedRevenue('2026-10',services,projects,expressJobs).some(i=>i.source==='express')).toBe(false));
 it('excluye quote de octubre del forecast de septiembre',()=>{const quote={...quotes[0],closeDate:'2026-10-10',stages:[]} as Quote;expect(calculateMonthlyForecast(month,[],[quote]).commercialWeighted).toBe(0)});
 it('no cuenta un quote convertido',()=>{const quote={...quotes[0],convertedProjectId:'p'};expect(calculateMonthlyForecast(month,[],[quote]).potential).toBe(0)});
 it('no regenera una etapa facturada',()=>{const ps=projects.map(p=>({...p,stages:p.stages.map(s=>s.id==='s-eco-3'?{...s,status:'facturada' as const,invoiceId:'i'}:s)}));expect(generateExpectedRevenue(month,services,ps,[]).some(i=>i.sourceId==='s-eco-3')).toBe(false)});
 it('impide facturar dos veces el mismo origen',()=>{const source={type:'express' as const,id:'e1',clientId:'datco',amount:180000,concept:'Corrección',date:'2026-09-01'};const invoice=createInvoiceFromRevenueSource(source,[]);expect(()=>createInvoiceFromRevenueSource(source,[invoice])).toThrow(/ya tiene/)});
 it('pago completo cobra invoice y sincroniza stage',()=>{const invoice:Invoice={id:'i',clientId:'ecobags',date:'2026-09-01',amount:100,number:'1',concept:'Etapa',origin:'projectStage',originId:'s-eco-3',status:'pendiente'};const payment:Payment={id:'p',invoiceId:'i',date:'2026-09-02',amount:100,method:'transferencia'};const updated=applyPayment(invoice,[],payment);expect(updated.status).toBe('cobrada');expect(syncProjectStageFromInvoice(projects,updated).flatMap(p=>p.stages).find(s=>s.id==='s-eco-3')?.status).toBe('cobrada')});
 it('pago parcial mantiene invoice parcial',()=>{const invoice:Invoice={id:'i',clientId:'x',date:'2026-09-01',amount:100,number:'1',concept:'x',origin:'manual',status:'pendiente'};expect(applyPayment(invoice,[],{id:'p',invoiceId:'i',date:'2026-09-02',amount:40,method:'transferencia'}).status).toBe('parcial')});
 it('nota de crédito descuenta sólo facturación neta',()=>{const invoice:Invoice={id:'i',clientId:'x',date:'2026-09-01',amount:100,number:'1',concept:'x',origin:'manual',status:'pendiente'};expect(getNetBilling([invoice],[{id:'c',clientId:'x',date:'2026-09-02',amount:20,number:'NC1',concept:'ajuste'}])).toEqual({gross:100,creditNotes:20,net:80})});
 it('cambiar monthlyTarget modifica insight',()=>{const forecast=calculateMonthlyForecast(month,generateExpectedRevenue(month,services,projects,expressJobs),[]);const low=generateFinancialInsights({clients,projects,quotes:[],invoices:[],month,settings:{...settings,monthlyTarget:1},forecast});const high=generateFinancialInsights({clients,projects,quotes:[],invoices:[],month,settings:{...settings,monthlyTarget:99999999},forecast});expect(low.at(-1)?.type).toBe('MONTH_ABOVE_TARGET');expect(high.at(-1)?.type).toBe('MONTH_BELOW_TARGET')});
 it('calcula correctamente la comparación anual',()=>expect(calculatePeriodComparison(28813253,14364518).percentageDifference).toBeCloseTo(100.59,2));
 it('una etapa sin importe no suma cero engañoso y queda pendiente',()=>{const forecast=calculateMonthlyForecast(month,generateExpectedRevenue(month,services,projects,[]),[]);expect(forecast.undefinedCount).toBe(4);expect(forecast.floor).toBe(3077245)});
});
