import type {AppSettings, Client, CreditNote, ExpectedRevenueItem, ExpressJob, Insight, Invoice, ManualExpectedIncome, MonthlyRevenueSnapshot, Payment, Project, Quote, RecurringService, RevenueForecast} from './types';

export const calculateQuoteWeightedValue = (quote: Quote) => quote.amount * quote.probability / 100;
const openQuote = (quote: Quote) => !quote.archived && !quote.convertedProjectId && !['rechazado', 'vencido'].includes(quote.status);

export function generateExpectedRevenue(month: string, services: RecurringService[], projects: Project[], expressJobs: ExpressJob[] = [], manual: ManualExpectedIncome[] = []): ExpectedRevenueItem[] {
  const recurring = services.filter(service => service.active && !service.archived).map(service => ({id: `exp-${month}-${service.id}`, clientId: service.clientId, month, amount: service.expectedAmount, source: 'recurrente' as const, sourceId: service.id, description: service.description, certainty: (service.variability === 'variable' ? 'probable' : 'asegurado') as 'probable' | 'asegurado', status: (service.expectedAmount === null ? 'revisión' : 'esperado') as 'revisión' | 'esperado'}));
  const stages = projects.filter(project => !project.archived && project.status !== 'cancelado').flatMap(project => project.stages.filter(stage => stage.expectedMonth === month && !stage.invoiceId && !['facturada', 'cobrada'].includes(stage.status)).map(stage => ({id: `exp-${stage.id}`, clientId: project.clientId, month, amount: stage.amount, source: 'projectStage' as const, sourceId: stage.id, description: stage.description, certainty: 'asegurado' as const, status: (stage.amount === null ? 'revisión' : 'esperado') as 'revisión' | 'esperado'})));
  const express = expressJobs.filter(job => !job.archived && job.date.slice(0, 7) === month && !job.invoiceId && !['facturado', 'cobrado'].includes(job.status)).map(job => ({id: `exp-${job.id}`, clientId: job.clientId, month, amount: job.amount, source: 'express' as const, sourceId: job.id, description: job.description, certainty: (job.status === 'pendiente' ? 'probable' : 'asegurado') as 'probable' | 'asegurado', status: 'esperado' as const}));
  const others = manual.filter(item => !item.archived && item.month === month && !item.invoiceId).map(item => ({id: `exp-${item.id}`, clientId: item.clientId, month, amount: item.amount, source: 'otro' as const, sourceId: item.id, description: item.description, certainty: (item.confirmed ? 'asegurado' : 'probable') as 'asegurado' | 'probable', status: (item.amount === null ? 'revisión' : 'esperado') as 'revisión' | 'esperado'}));
  return [...recurring, ...stages, ...express, ...others];
}

export function calculateMonthlyForecast(month: string, items: ExpectedRevenueItem[], quotes: Quote[]): RevenueForecast {
  const active = items.filter(item => item.month === month && item.status !== 'omitido' && !item.invoiceId);
  const floor = active.filter(item => item.certainty === 'asegurado').reduce((sum, item) => sum + (item.amount ?? 0), 0);
  const probableItems = active.filter(item => item.certainty === 'probable').reduce((sum, item) => sum + (item.amount ?? 0), 0);
  const periodQuotes = quotes.filter(quote => openQuote(quote) && (quote.stages[0]?.expectedMonth ?? quote.closeDate.slice(0, 7)) === month);
  const commercialWeighted = periodQuotes.reduce((sum, quote) => sum + calculateQuoteWeightedValue(quote), 0);
  return {floor, probable: floor + probableItems + commercialWeighted, potential: floor + probableItems + periodQuotes.reduce((sum, quote) => sum + quote.amount, 0), undefinedCount: active.filter(item => item.amount === null).length, commercialWeighted};
}

export function calculatePeriodComparison(current: number, previous: number) {return {current, previous, absoluteDifference: current - previous, percentageDifference: previous === 0 ? null : (current - previous) / previous * 100};}
export const getYearToDateRevenue = (snapshots: MonthlyRevenueSnapshot[], year: number, throughMonth = 12) => snapshots.filter(item => item.month.startsWith(`${year}-`) && Number(item.month.slice(5)) <= throughMonth).reduce((sum, item) => sum + item.amount, 0);
export const getMonthlyAverage = (snapshots: MonthlyRevenueSnapshot[], year: number) => {const rows = snapshots.filter(item => item.month.startsWith(`${year}-`)); return rows.length ? rows.reduce((sum, item) => sum + item.amount, 0) / rows.length : 0;};
export const getRecurringBase = (services: RecurringService[]) => services.filter(item => item.active && !item.archived).reduce((sum, item) => sum + (item.expectedAmount ?? 0), 0);
export const getClientRevenue = (clientId: string, invoices: Invoice[], creditNotes: CreditNote[] = []) => invoices.filter(item => item.clientId === clientId && !item.archived).reduce((sum, item) => sum + item.amount, 0) - creditNotes.filter(item => item.clientId === clientId && !item.archived).reduce((sum, item) => sum + item.amount, 0);
export const getCollectedAmount = (payments: Payment[]) => payments.filter(item => !item.archived).reduce((sum, item) => sum + item.amount, 0);
export const getOutstandingAmount = (invoices: Invoice[], payments: Payment[]) => invoices.filter(item => !item.archived).reduce((sum, invoice) => sum + Math.max(0, invoice.amount - payments.filter(payment => !payment.archived && payment.invoiceId === invoice.id).reduce((paid, payment) => paid + payment.amount, 0)), 0);
export const getNetBilling = (invoices: Invoice[], creditNotes: CreditNote[]) => ({gross: invoices.filter(item => !item.archived).reduce((sum, item) => sum + item.amount, 0), creditNotes: creditNotes.filter(item => !item.archived).reduce((sum, item) => sum + item.amount, 0), net: invoices.filter(item => !item.archived).reduce((sum, item) => sum + item.amount, 0) - creditNotes.filter(item => !item.archived).reduce((sum, item) => sum + item.amount, 0)});

type InvoiceSource = {type: Invoice['origin']; id: string; clientId: string; amount: number | null; concept: string; date: string};
export function createInvoiceFromRevenueSource(source: InvoiceSource, invoices: Invoice[]): Invoice {
  if (source.amount === null) throw new Error('El ingreso no tiene importe definido');
  if (invoices.some(invoice => invoice.origin === source.type && invoice.originId === source.id && !invoice.archived)) throw new Error('Este ingreso ya tiene una factura vinculada');
  return {id: crypto.randomUUID(), clientId: source.clientId, date: source.date, amount: source.amount, number: `INT-${invoices.length + 1}`, concept: source.concept, origin: source.type, originId: source.id, status: 'pendiente'};
}

export function applyPayment(invoice: Invoice, existing: Payment[], payment: Payment, allowOverpayment = false) {
  const paid = existing.filter(item => item.invoiceId === invoice.id && !item.archived).reduce((sum, item) => sum + item.amount, 0);
  if (!allowOverpayment && paid + payment.amount > invoice.amount) throw new Error('El cobro supera el saldo de la factura');
  return {...invoice, status: paid + payment.amount >= invoice.amount ? 'cobrada' as const : 'parcial' as const};
}
export function syncProjectStageFromInvoice(projects: Project[], invoice: Invoice): Project[] {if (invoice.origin !== 'projectStage' || !invoice.originId) return projects; return projects.map(project => ({...project, stages: project.stages.map(stage => stage.id === invoice.originId ? {...stage, invoiceId: invoice.id, status: invoice.status === 'cobrada' ? 'cobrada' : 'facturada'} : stage)}));}
export function calculateClientConcentration(invoices: Invoice[]) {const total = invoices.reduce((sum, item) => sum + item.amount, 0); return Object.entries(invoices.reduce<Record<string, number>>((acc, item) => ({...acc, [item.clientId]: (acc[item.clientId] ?? 0) + item.amount}), {})).map(([clientId, amount]) => ({clientId, amount, share: total ? amount / total : 0})).sort((a, b) => b.share - a.share);}
export function generateFinancialInsights(input: {clients: Client[]; projects: Project[]; quotes: Quote[]; invoices: Invoice[]; month: string; settings: AppSettings; forecast: RevenueForecast; today?: string}): Insight[] {const out: Insight[] = []; const concentration = calculateClientConcentration(input.invoices)[0]; if (concentration && concentration.share * 100 > input.settings.concentrationThreshold) out.push({id: 'concentration', type: 'CLIENT_CONCENTRATION', severity: 'warning', message: `${input.clients.find(c => c.id === concentration.clientId)?.name} representa ${Math.round(concentration.share * 100)}% de tu facturación individual.`, action: 'Ver cliente', actionType: 'navigate', entityType: 'client', entityId: concentration.clientId}); input.projects.flatMap(project => project.stages.map(stage => ({project, stage}))).filter(row => row.stage.expectedMonth === input.month && row.stage.amount === null).forEach(({project, stage}) => out.push({id: stage.id, type: 'PROJECT_STAGE_DUE', severity: 'warning', message: `No definiste el importe de ${stage.name} · ${project.name}.`, action: 'Definir importe', actionType: 'edit', entityType: 'projectStage', entityId: stage.id})); out.push({id: 'target', type: input.forecast.probable >= input.settings.monthlyTarget ? 'MONTH_ABOVE_TARGET' : 'MONTH_BELOW_TARGET', severity: input.forecast.probable >= input.settings.monthlyTarget ? 'positive' : 'info', message: input.forecast.probable >= input.settings.monthlyTarget ? 'La proyección probable supera tu objetivo mensual.' : 'La proyección probable aún está debajo del objetivo.', action: 'Ver oportunidades', actionType: 'navigate', entityType: 'quote'}); return out;}
export const calculateAnnualProjection = (actual: number, forecast: RevenueForecast, remainingMonths = 4) => ({conservative: actual + forecast.floor * remainingMonths, probable: actual + forecast.probable * remainingMonths, potential: actual + forecast.potential * remainingMonths});
export function matchInvoiceToExpectedRevenue(invoice: Invoice, items: ExpectedRevenueItem[]) {return items.map(item => ({item, score: (item.clientId === invoice.clientId ? 60 : 0) + (item.amount === invoice.amount ? 30 : 0) + (item.month === invoice.date.slice(0, 7) ? 10 : 0)})).sort((a, b) => b.score - a.score)[0];}
