'use client';
import {createContext,useContext,useEffect,useMemo,useState} from 'react';
import * as seed from '@/data/seed';
import type {AppSettings,Client,CreditNote,ExpressJob,InboxItem,Invoice,ManualExpectedIncome,MonthlyRevenueSnapshot,Payment,Project,Quote,RecurringService} from '@/domain/types';
type State={clients:Client[];services:RecurringService[];projects:Project[];quotes:Quote[];expressJobs:ExpressJob[];invoices:Invoice[];payments:Payment[];creditNotes:CreditNote[];manualExpectedIncome:ManualExpectedIncome[];inbox:InboxItem[];snapshots:MonthlyRevenueSnapshot[];settings:AppSettings;selectedPeriod:string};
type Collections=Omit<State,'settings'|'selectedPeriod'|'snapshots'>; type Ctx=State&{ready:boolean;save:<K extends keyof Collections>(k:K,v:Collections[K][number])=>void;archive:<K extends keyof Collections>(k:K,id:string)=>void;saveSettings:(settings:AppSettings)=>void;setSelectedPeriod:(period:string)=>void;replaceProjects:(projects:Project[])=>void;reset:()=>void};
const currentPeriod=()=>new Date().toISOString().slice(0,7);
const initial:State={clients:seed.clients,services:seed.services,projects:seed.projects,quotes:seed.quotes,expressJobs:seed.expressJobs,invoices:seed.invoices,payments:seed.payments,creditNotes:seed.creditNotes,manualExpectedIncome:seed.manualExpectedIncome,inbox:seed.inbox,snapshots:seed.snapshots,settings:seed.settings,selectedPeriod:currentPeriod()};
const Context=createContext<Ctx|null>(null);const KEY='nexo-freelance-os-v2';
function migrate(value:Partial<State>):State{return {...initial,...value,creditNotes:value.creditNotes??[],manualExpectedIncome:value.manualExpectedIncome??[],snapshots:value.snapshots?.length?value.snapshots:seed.snapshots,settings:{...seed.settings,...value.settings},selectedPeriod:value.selectedPeriod??currentPeriod(),projects:(value.projects??initial.projects).map(project=>({...project,stages:project.stages.map(stage=>({...stage,status:(stage.status as string)==='lista'?'lista_para_facturar':stage.status,invoiceId:stage.invoiceId}))}))} as State}
export function AppProvider({children}:{children:React.ReactNode}){const[state,setState]=useState(initial);const[ready,setReady]=useState(false);useEffect(()=>{const raw=localStorage.getItem(KEY)??localStorage.getItem('nexo-freelance-os-v1');if(raw)try{setState(migrate(JSON.parse(raw) as Partial<State>))}catch{setState(initial)}setReady(true)},[]);const persist=(next:State)=>{setState(next);localStorage.setItem(KEY,JSON.stringify(next))};const value=useMemo<Ctx>(()=>({...state,ready,save:(key,value)=>persist({...state,[key]:[...(state[key] as {id:string}[]).filter(item=>item.id!==value.id),value]}),archive:(key,id)=>persist({...state,[key]:(state[key] as ({id:string;archived?:boolean}[])).map(item=>item.id===id?{...item,archived:true}:item)}),saveSettings:settings=>persist({...state,settings}),setSelectedPeriod:selectedPeriod=>persist({...state,selectedPeriod}),replaceProjects:projects=>persist({...state,projects}),reset:()=>{localStorage.removeItem(KEY);setState(initial)}}),[state,ready]);return <Context.Provider value={value}>{children}</Context.Provider>}
export const useApp=()=>{const context=useContext(Context);if(!context)throw Error('Provider missing');return context};
